[package]
name = "title_grabber_rs"
version = "0.1.0"
authors = ["Cristian Rasch <cristianrasch@fastmail.fm>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
num_cpus = "1.0"
lazy_static = "1.3.0"
regex = "1"
reqwest = "0.9.14"
